title: Process code for software procurement

remote_theme: publiccodenet/jekyll-theme

include:
  - "LICENSE.md"

toc: true

baseurl: /process-code-software-procurement

defaults:
  -
    scope:
      path: '/phases/*'
    values:
      breadcrumbs:
        - name: 'Phases'
          path: '/phases/'
      show_prev_next: false # We'll use a custom prev-next navigation instead

  -
    scope:
      path: '/'
    values:
      breadcrumbs: true
